import { db, usersTable } from "@workspace/db";
import { logger } from "./logger";

const DEMO_USERS = [
  // --- 6 FEMALE USERS ---
  {
    fullName: "Emma Johnson",
    gender: "Female",
    interestedIn: "Male",
    age: 26,
    city: "New York",
    bio: "Coffee addict and weekend hiker. Looking for someone who loves adventures as much as lazy Sunday mornings.",
    profileImage: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&q=80",
    loginType: "gmail",
    usernameOrEmail: "emma@gmail.com",
    password: "Demo123",
    interests: ["Hiking", "Coffee", "Photography", "Travel", "Yoga"],
    verified: true,
    isOnline: true,
  },
  {
    fullName: "Sophia Martinez",
    gender: "Female",
    interestedIn: "Male",
    age: 24,
    city: "Los Angeles",
    bio: "Actress by day, foodie by night. I believe life is too short for bad food and boring conversations.",
    profileImage: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&q=80",
    loginType: "gmail",
    usernameOrEmail: "sophia@gmail.com",
    password: "Demo123",
    interests: ["Acting", "Food", "Music", "Beaches", "Art"],
    verified: true,
    isOnline: false,
  },
  {
    fullName: "Olivia Chen",
    gender: "Female",
    interestedIn: "Male",
    age: 28,
    city: "San Francisco",
    bio: "UX designer who sketches wireframes on napkins. I talk with my hands and think with my heart.",
    profileImage: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&q=80",
    loginType: "gmail",
    usernameOrEmail: "olivia@gmail.com",
    password: "Demo123",
    interests: ["Design", "Cycling", "Cooking", "Meditation", "Books"],
    verified: false,
    isOnline: true,
  },
  {
    fullName: "Emma Williams",
    gender: "Female",
    interestedIn: "Male",
    age: 23,
    city: "Chicago",
    bio: "Med student surviving on iced lattes and ambition. My love language is memes.",
    profileImage: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&q=80",
    loginType: "instagram",
    usernameOrEmail: "@emma_life",
    password: "Insta123",
    interests: ["Medicine", "Running", "Memes", "Concerts", "Dogs"],
    verified: true,
    isOnline: true,
  },
  {
    fullName: "Sophia Kim",
    gender: "Female",
    interestedIn: "Male",
    age: 27,
    city: "Seattle",
    bio: "Barista turned photographer. I see the world through golden hour light.",
    profileImage: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&q=80",
    loginType: "instagram",
    usernameOrEmail: "@sophia.xx",
    password: "Insta123",
    interests: ["Photography", "Coffee", "Music", "Skateboarding", "Vintage"],
    verified: false,
    isOnline: false,
  },
  {
    fullName: "Olivia Davis",
    gender: "Female",
    interestedIn: "Male",
    age: 25,
    city: "Austin",
    bio: "Startup founder. Obsessed with burritos, live music, and making the world a little better.",
    profileImage: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?w=600&q=80",
    loginType: "instagram",
    usernameOrEmail: "@olivia_21",
    password: "Insta123",
    interests: ["Startups", "Music", "Burritos", "Rock Climbing", "Coding"],
    verified: true,
    isOnline: true,
  },
  // --- 6 MALE USERS ---
  {
    fullName: "James Anderson",
    gender: "Male",
    interestedIn: "Female",
    age: 29,
    city: "New York",
    bio: "Finance by day, jazz guitarist by night. Believe every great story starts with a great first date.",
    profileImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=600&q=80",
    loginType: "gmail",
    usernameOrEmail: "james@gmail.com",
    password: "Demo123",
    interests: ["Jazz", "Finance", "Guitar", "Wine", "Travel"],
    verified: true,
    isOnline: false,
  },
  {
    fullName: "Ethan Brooks",
    gender: "Male",
    interestedIn: "Female",
    age: 27,
    city: "Los Angeles",
    bio: "Filmmaker chasing sunsets and stories. Will make you a short film for your birthday.",
    profileImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80",
    loginType: "gmail",
    usernameOrEmail: "ethan@gmail.com",
    password: "Demo123",
    interests: ["Film", "Surfing", "Photography", "Cooking", "Architecture"],
    verified: true,
    isOnline: true,
  },
  {
    fullName: "Noah Thompson",
    gender: "Male",
    interestedIn: "Female",
    age: 25,
    city: "San Francisco",
    bio: "Software engineer at a startup. I can fix bugs but not my inability to resist a good book.",
    profileImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=600&q=80",
    loginType: "gmail",
    usernameOrEmail: "noah@gmail.com",
    password: "Demo123",
    interests: ["Coding", "Reading", "Climbing", "Coffee", "Board Games"],
    verified: false,
    isOnline: true,
  },
  {
    fullName: "James Walker",
    gender: "Male",
    interestedIn: "Female",
    age: 30,
    city: "Chicago",
    bio: "Personal trainer and nutrition coach. I promise I only talk about fitness 60% of the time.",
    profileImage: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&q=80",
    loginType: "instagram",
    usernameOrEmail: "@james.fit",
    password: "Insta123",
    interests: ["Fitness", "Nutrition", "Hiking", "Cooking", "Podcasts"],
    verified: true,
    isOnline: false,
  },
  {
    fullName: "Ethan Rivera",
    gender: "Male",
    interestedIn: "Female",
    age: 26,
    city: "Miami",
    bio: "Graphic designer with a thing for typefaces and tacos. Let's debate serif vs sans-serif over drinks.",
    profileImage: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80",
    loginType: "instagram",
    usernameOrEmail: "@ethan_official",
    password: "Insta123",
    interests: ["Design", "Typography", "Tacos", "Skating", "Music"],
    verified: true,
    isOnline: true,
  },
  {
    fullName: "Noah Carter",
    gender: "Male",
    interestedIn: "Female",
    age: 28,
    city: "Austin",
    bio: "Environmental scientist and weekend camper. I can name every star in the Big Dipper.",
    profileImage: "https://images.unsplash.com/photo-1463453091185-61582044d556?w=600&q=80",
    loginType: "instagram",
    usernameOrEmail: "@noah_07",
    password: "Insta123",
    interests: ["Environment", "Camping", "Astronomy", "Kayaking", "Cooking"],
    verified: false,
    isOnline: false,
  },
];

export async function seedDatabase(): Promise<void> {
  const existing = await db.select().from(usersTable).limit(1);
  if (existing.length > 0) {
    logger.info("Database already seeded, skipping.");
    return;
  }

  logger.info("Seeding demo users...");
  for (const user of DEMO_USERS) {
    await db.insert(usersTable).values(user);
  }
  logger.info({ count: DEMO_USERS.length }, "Seeding complete.");
}
